version: '3.0'
services:
  jingo:
    build:
      context: .
    environment:
      - WATCHPACK_POLLING
    networks:
      - jingo-net
    expose:
      - ${FRONTEND_PORT_HOST}

networks:
  jingo-net:
    driver: bridge