version: '3.0'
services:
  jingo:
    build:
      context: .
    ports:
      - ${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}
    environment:
      - WATCHPACK_POLLING
    networks:
      - jingo-net

networks:
  jingo-net:
    driver: bridge