version: '3.0'
services:
  bingo:
    build:
      context: .
    environment:
      - WATCHPACK_POLLING
    networks:
      - bingo-net
    hostname: bingo
    expose:
      - ${FRONTEND_PORT_CONTAINER}
    ports:
      - ${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}

networks:
  bingo-net:
    driver: bridge

# Command to run:
# docker-compose -f docker-compose.yml build; docker-compose -f docker-compose.yml up -d; docker-compose logs -f