name: Block PR to main not from dev

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Check source branch is 'dev'"
        run: "[ ${GITHUB_REF} ==  'dev' ]"
      - name: "Close PR automatically"
        if: ${{ failure }}
        run: echo "Close!"
        
