name: Bump tag on push

on:
  push:
    branches: [main, dev]

jobs:
  bump-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up environment"
        id: set-up-env
        run: |
          # Set up semver
          wget -O /usr/local/bin/semver \
          https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

          # Set up environment
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=BUMP_LEVEL::minor"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            echo "::set-output name=BUMP_LEVEL::patch"
          else
             echo "::set-output name=BUMP_LEVEL::release"
          fi         
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.set-up-env.outputs.BUMP_LEVEL }}

      # - name: "Get previous tag"
      #   id: get-previous-tag
      #   run: |
      #     echo "$(git describe --tags --abbrev=0)"
      #     echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"
      # - name: "Bump tag"
      #   id: bump-tag
      #   run: |
      #     echo "::set-output name=NEW_TAG::$(semver bump ${{ steps.set-up-env.outputs.BUMP_LEVEL }} ${{ steps.get-previous-tag.outputs.TAG }})"
      # - name: "Output preivious tag"
      #   run: echo "Bumping tag (${{ steps.set-up-env.outputs.BUMP_LEVEL }}) ${{ steps.get-previous-tag.outputs.TAG }} -> ${{ steps.bump-tag.outputs.NEW_TAG }}"