name: Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/${TARGET_ENV}.key
          chmod 600 ~/.ssh/${TARGET_ENV}.key
          cat >>~/.ssh/config <<END
          Host ${TARGET_ENV}
            HostName ${SSH_HOST}
            User ${SSH_USER}
            IdentityFile ~/.ssh/${TARGET_ENV}.key
            StrictHostKeyChecking no
          END
        env:
          TARGET_ENV: prod
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      - name: Test SSH
        run: ssh ${TARGET_ENV} echo ok
        env:
          TARGET_ENV: prod