name: Deploy Test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/${TARGET_ENV}.key
          chmod 600 ~/.ssh/${TARGET_ENV}.key
          cat >>~/.ssh/config <<END
          Host ${TARGET_ENV}
            HostName ${SSH_HOST}
            User ${SSH_USER}
            IdentityFile ~/.ssh/${TARGET_ENV}.key
            StrictHostKeyChecking no
          END
        env:
          TARGET_ENV: test
          SSH_USER: ${{ secrets.TEST_SSH_USER }}
          SSH_HOST: ${{ secrets.TEST_SSH_HOST }}
          SSH_KEY: ${{ secrets.TEST_SSH_KEY }}
      - name: Recreate Docker Compose (SSH)
        run: ssh ${TARGET_ENV} "cd /opt/bingo-test; git pull; docker-compose build; docker-compose up -d"
        env:
          TARGET_ENV: test