name: Bump tag on push

on:
  push:
    branches: [main, dev]

jobs:
  bump-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up environment"
        id: set-up-env
        run: |
          # Set up environment
          if [[ "${{ github.ref_name }}" = "main" ]]; then
            echo "::set-output name=BUMP_LEVEL::minor"
            echo "::set-output name=SSH_USER::${{ secrets.PROD_SSH_USER }}
            echo "::set-output name=SSH_HOST::${{ secrets.PROD_SSH_HOST }}
            echo "::set-output name=SSH_KEY::${{ secrets.PROD_SSH_KEY }}
          elif [[ "${{ github.ref_name }}" = "dev" ]]; then
            echo "::set-output name=BUMP_LEVEL::patch"
            echo "::set-output name=SSH_USER::${{ secrets.TEST_SSH_USER }}
            echo "::set-output name=SSH_HOST::${{ secrets.TEST_SSH_HOST }}
            echo "::set-output name=SSH_KEY::${{ secrets.TEST_SSH_KEY }}
          else
            echo "Unexpected branch"
            exit 1
          fi         
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.set-up-env.outputs.BUMP_LEVEL }}
          release_branches: main,dev
      - name: Deploy (mock)
        run: echo ${{ steps.set-up-env.outputs.SSH_USER }} ${{ steps.set-up-env.outputs.SSH_HOST }}