name: Bump tag on push

on:
  push:
    branches: [main, dev]

jobs:
  bump-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up environment (prod)
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "BUMP_LEVEL=minor" >> $GITHUB_ENV
          echo "SSH_USER_SECRET=PROD_SSH_USER" >> $GITHUB_ENV
          echo "SSH_HOST_SECRET=PROD_SSH_HOST" >> $GITHUB_ENV
          echo "SSH_KEY_SECRET=PROD_SSH_KEY" >> $GITHUB_ENV
      - name: Set up environment (dev)
        if: ${{ github.ref_name == 'dev' }}
        run: |
          echo "BUMP_LEVEL=patch" >> $GITHUB_ENV
          echo "SSH_USER_SECRET=TEST_SSH_USER" >> $GITHUB_ENV
          echo "SSH_HOST_SECRET=TEST_SSH_HOST" >> $GITHUB_ENV
          echo "SSH_KEY_SECRET=TEST_SSH_KEY" >> $GITHUB_ENV
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.BUMP_LEVEL }}
          release_branches: main,dev
      - name: Deploy (mock)
        run: echo ${{ secrets[${env.SSH_USER_SECRET}] }} ${{ secrets[${env.SSH_HOST_SECRET} }}