name: Release

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Set up environment"
        run: |
          wget -O /usr/local/bin/semver \
          https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver

          # Make script executable
          chmod +x /usr/local/bin/semver

          # Prove it works
          semver --version
      - name: "Get previous tag"
        id: get-previous-tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"
      - name: "Print preivious tag"
        run: echo "Prev tag ${{ steps.get-previous-tag.TAG }}"